### ISSUE TITLE
Location Tree Data not Asynchronous after Add New Location

### ISSUE THREAD

**Issue by sandershihacker** [OpenChirp/website#12]
After adding new location, a page refresh is needed to update the tree view.

**Comment by sandershihacker** [comment]
Never mind, it just takes a couple seconds.

**Comment by sandershihacker** [comment]
Only works after another API call.

**Comment by khush-bhatia** [comment]
When you do the POST call to create the child location, it will return the created location in response. You could add the object returned in response to parentLocation.children.( This is equivalent to making another API call.)
