### ISSUE TITLE
Services page should show list of linked devices

### ISSUE THREAD

**Issue by linux4life798** [OpenChirp/website#122]
A service page should probably show a nice list of devices that have linked it.

This should just require another rest request to get service/service_id_blah/things.
I hope the rest interface allows you to fetch the "things" if you are the service owner or admin.

**Comment by hiliang-cmu** [comment]
Current service object model does not include devices. Added issue on rest interface to tie them together.

**Comment by hiliang-cmu** [comment]
Ignore referenced issue, found the appropriate request on rest interface

**Comment by hiliang-cmu** [comment]
What fields would be useful in this list besides device name?

**Comment by linux4life798** [comment]
Ideally, Device Name, its Service Config, and Device Owner, and Device
Location.

Based on the info readily available from the rest request, I think Device
Name (with click link to the device page) and Service Config is sufficient
for now.

**Comment by hiliang-cmu** [comment]
> I think Device Name (with click link to the device page) and Service Config is sufficient for now.

Service Config is a set of key:value pairs right? Should each config key specific to that service be columnized then? e.g.

Device Name | Key1 | Key2 | Key3
- | - | - | -
Device 1 | Val1 | Val2 | Val3
Device 2 | Val1 | Val2 | Val3

**Comment by linux4life798** [comment]
I forgot actually one other pretty important property that should be shown in the service page. The `Device's Service-Link Status`. This might require some new handcrafted rest request.

Yes, service config is currently an array of key/value objects. Ah, I think it might be ok to hide the service config behind a button click and a dialog-box, like we do in the Device's Service page.

**Comment by hiliang-cmu** [comment]
- ID
- Name
- Service.status
- Owner.name
- Owner.email
- Location.name

**Comment by linux4life798** [comment]
@hiliang-cmu crushed this
