### ISSUE TITLE
Last value timestamp seconds

### ISSUE THREAD

**Issue by linux4life798** [OpenChirp/website#123]
I think the last value timestamp format should include seconds, similar to last updated timestamp.

I am often debugging within the minute and can't tell is the value is being updated until the minute ticks over.

**Comment by hiliang-cmu** [comment]
Is this only for Device-Transducer tab? There's a few other timestamps for service status here and there.

**Comment by linux4life798** [comment]
Yes. I was thinking it would only be useful for the Transducers tab.

**Comment by linux4life798** [comment]
That referenced commit looks good. Ready to pull when you are.
