### ISSUE TITLE
hapijs / hoek 2.16.4 Vulnerability

### ISSUE THREAD

**Issue by ABalanuta** [OpenChirp/website#130]
There is a security vulnerability by using the mentioned package. We should upgrade it.

**Comment by hiliang-cmu** [comment]
```
  Moderate        Prototype pollution

  Package         hoek

  Dependency of   protractor [dev]

  Path            protractor > webdriver-manager > request > hawk > sntp > hoek

  More info       https://nodesecurity.io/advisories/566
```

Though that's deduped from `@angular/cli@1.7.4 > less > request > hawk > hoek`

**Comment by hiliang-cmu** [comment]
Closing this as even with latest versions of all direct dependency packages, an `npm audit` will show that 5 levels down, there are some outdated/vulnerable ones such as hoek. However, none of these rise above "moderate" severity and especially as used by our client interface.
