### ISSUE TITLE
Restrict transducers shown on Visualization page

### ISSUE THREAD

**Issue by linux4life798** [OpenChirp/website#141]
There needs to be a way to restrict which transducers are shown on the Visualization page.

I propose using Checkboxes similar to https://material.angularjs.org/latest/demo/checkbox#syncing on top of the visualization iframe to select which transducers are to be shown.

**Comment by hiliang-cmu** [comment]
Resolved by f6316d1136976b01d257b914132f1619e2fd5a94

**Comment by linux4life798** [comment]
Awesome
