### ISSUE TITLE
Location tree item onClick

### ISSUE THREAD

**Issue by linux4life798** [OpenChirp/website#155]
When expanding a location tree item, it seems that you must click on the left side, closest to the text to have it expand.
This should be fixed to allow clicking anywhere on the location tree item (except the three dots).

**Comment by sandershihacker** [comment]
Over [here](https://github.com/OpenChirp/website/blob/master/src/app/components/locationtree/tree.component.html), you can do the following: move the `click` action in **line 3** to the `div` tag in **line 2**. Then set the `z-index` of the `mat-menu` tag in **line 7** to something like `999` to be above the `tree-node div` when it appears.

**Comment by linux4life798** [comment]
Awesome. Thanks Sander!

**Comment by linux4life798** [comment]
@hiliang-cmu could you try this?

**Comment by hiliang-cmu** [comment]
The matMenu already pops out into some other overlay container, so that's ok. Added stopPropogation to the mat-icon.
