### ISSUE TITLE
Display properties of devices/transducers as key value pair 

### ISSUE THREAD

**Issue by khush-bhatia** [OpenChirp/website#25]
Almost all resources ( devices, transducers, services, gateway) have a properties object that can contain any number of key: value pairs. Need an elegant solution on the website to add/update/remove these properties.

**Comment by sandershihacker** [comment]
Need more insight on what "elegant means."

**Comment by khush-bhatia** [comment]
@sandershihacker Sander, for now can you show all the properties in one input box (The content would be a json)? We can make it better later.

**Comment by sandershihacker** [comment]
I have an idea on how to design a component for all properties, the only problem is that none of the data seems to have the properties field, and I cannot add that field to them.
