### ISSUE TITLE
Device templates

### ISSUE THREAD

**Issue by khush-bhatia** [OpenChirp/website#26]
Add a link in the left menu for device templates. Clicking it should list all templates and each device template name should be clickable with more details about it.

Link to rest api doc
https://openchirp.github.io/api_doc/#device-template

**Comment by sandershihacker** [comment]
Uh okay, but what's a device template?

**Comment by sandershihacker** [comment]
Will create component for a device template list, and have a router link on the left menu.

**Comment by khush-bhatia** [comment]
We also need the following
1. On any device's page, there should be a Save as Template and Delete button. Save as template button should ask for a name and description of the template.
2. On any device template's page, there should be a button to create a device using that template.

**Comment by sandershihacker** [comment]
Link created, can list templates which are clickable.

**Comment by sandershihacker** [comment]
Can create device from template page.

**Comment by sandershihacker** [comment]
Delete Functionality Complete.

**Comment by khush-bhatia** [comment]
Sander,
This is great. Can you please merge the latest to the Openchirp/website
branch. I will be using that to deploy the website on
openchirp.andrew.cmu.edu.

Thanks
Khushboo
