### ISSUE TITLE
Use ng2-data-table for transducer and commands page

### ISSUE THREAD

**Issue by khush-bhatia** [OpenChirp/website#69]
The idea is to use minimal div and css to style that page and to make it easy to add more columns.
Right now the page formatting goes off (and data becomes unreadable) on different screen resolutions/phones/non-chrome browsers.

**Comment by sandershihacker** [comment]
The use of tables does not fix formatting for small screen widths. However, it does reduce the amount of css code, and makes styles consistent across pages that use the table.

**Comment by sandershihacker** [comment]
To format for smaller screen widths, more design choices need to be made.
