### ISSUE TITLE
Embed transducer timeseries visualization

### ISSUE THREAD

**Issue by khush-bhatia** [OpenChirp/website#71]
Here is the link to grafana dashboard. 
http://openchirp.andrew.cmu.edu:3000/dashboard/script/transducer.js?device=<device_id>&transducer=<transducer_name>&theme=light&orgId=1&refresh=5s

Example link :
http://openchirp.andrew.cmu.edu:3000/dashboard/script/transducer.js?device=590b8ab0c1d7ee2313ee421c&transducer=door_state&theme=light&orgId=1&refresh=5s

**Comment by sandershihacker** [comment]
Where does this go, and what link should I link to in the iframe?

**Comment by khush-bhatia** [comment]
It should be a separate tab in devices.  Can you just hardcode the example link for now. I will customize it later.
