### ISSUE TITLE
Time Series Service Update issue

### ISSUE THREAD

**Issue by anthonyrowe** [OpenChirp/website#93]
I was just playing around with the time series and noticed something odd.  It looks like if you go to Location->CIC->Floor 2 and then to the "agr testing" device the time series DB is logging "door_state" fine, but not "Light" or "Strange".  This is most likely not the website and maybe just the Time Series Service?

**Comment by khush-bhatia** [comment]
The timeseries service is logging it but the database name in influxdb is all lowercase.
The script that generates the grafana graphs is still case-sensitive.

This problem should be resolved with the fix of
https://github.com/OpenChirp/openchirp_rest/issues/10

**Comment by anthonyrowe** [comment]
That makes sense.

**Comment by khush-bhatia** [comment]
Fixed issue in rest api:
OpenChirp/openchirp_rest#10
